# Generated by Django 5.0 on 2024-02-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nadmin', '0004_tb_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
            ],
        ),
    ]
