# Generated by Django 5.0 on 2024-02-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nadmin', '0005_tbl_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
