# Generated by Django 5.0 on 2024-02-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nadmin', '0010_tbl_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_gender', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=80)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nadmin.tbl_district')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nadmin.tbl_place')),
            ],
        ),
    ]
