# Generated by Django 5.0 on 2024-02-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nadmin', '0011_tbl_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newuser',
        ),
    ]
