# Generated by Django 5.0 on 2024-02-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nadmin', '0014_tbl_subcat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tb_location',
        ),
    ]
