# Generated by Django 5.0 on 2024-02-20 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ad',
        ),
    ]
