# Generated by Django 5.0 on 2024-02-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0006_tbl_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_event',
            name='merchant',
        ),
        migrations.DeleteModel(
            name='tbl_ad',
        ),
        migrations.DeleteModel(
            name='tbl_event',
        ),
    ]
