# Generated by Django 5.0 on 2024-02-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_event',
        ),
    ]
