# Generated by Django 5.0 on 2024-02-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0010_tbl_event'),
        ('User', '0022_delete_tbl_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ad',
        ),
    ]
