# Generated by Django 5.0 on 2024-02-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0014_tbl_ad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_event',
        ),
    ]
