# Generated by Django 5.0 on 2024-04-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0016_tbl_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_event',
        ),
    ]
