# Generated by Django 5.0 on 2024-04-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_chat'),
        ('Merchant', '0017_delete_tbl_event'),
        ('Nadmin', '0017_delete_tb_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=500)),
                ('event_description', models.CharField(max_length=500)),
                ('event_fromdate', models.DateField()),
                ('event_todate', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_status', models.IntegerField(default='0')),
                ('event_location', models.CharField(max_length=500)),
                ('event_image', models.FileField(upload_to='Assets/EventImage/')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_merchant')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nadmin.tbl_place')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nadmin.tbl_subcat')),
            ],
        ),
    ]
