# Generated by Django 5.0 on 2024-02-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_subject', models.CharField(max_length=500)),
                ('feedback_details', models.CharField(max_length=500)),
                ('feedback_postdate', models.DateField(auto_now_add=True)),
                ('feedback_status', models.IntegerField(default='0')),
            ],
        ),
    ]
