# Generated by Django 5.0 on 2024-02-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
