# Generated by Django 5.0 on 2024-02-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
