# Generated by Django 5.0 on 2024-02-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_tbl_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_review',
        ),
    ]
