# Generated by Django 5.0 on 2024-02-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_tbl_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_review',
        ),
    ]
