# Generated by Django 5.0 on 2024-02-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_tbl_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_review',
            name='ad',
        ),
    ]
