# Generated by Django 5.0 on 2024-02-13 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('Nadmin', '0011_tbl_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=30)),
                ('merchant_contact', models.CharField(max_length=30)),
                ('merchant_gender', models.CharField(max_length=30)),
                ('merchant_email', models.CharField(max_length=30)),
                ('merchant_password', models.CharField(max_length=30)),
                ('merchant_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('merchant_proof', models.FileField(upload_to='Assets/UserProof/')),
                ('merchant_status', models.IntegerField(default='0')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nadmin.tbl_place')),
            ],
        ),
    ]
