# Generated by Django 5.0 on 2024-02-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_merchant',
            name='merchant_proof',
        ),
    ]
