# Generated by Django 5.0 on 2024-02-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_remove_tbl_merchant_merchant_proof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_merchant',
        ),
    ]
