# Generated by Django 5.0 on 2024-02-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_merchant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
