# Generated by Django 5.0 on 2024-02-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='district',
        ),
    ]
